In [2]:
import pandas as pd

In [2]:
data = {
    'Product': ['Laptop', 'Shirt', 'Smartphone', 'Shoes', 'Headphones', 'Watch'],
    'Price': [999.99, 29.99, 599.99, 89.99, 199.99, 49.99],
    'Category': ['Electronics', 'Fashion', 'Electronics', 'Fashion', 'Electronics', 'Fashion']
}

In [3]:
df = pd.DataFrame(data)

In [4]:
df.head()

      Product   Price     Category
0      Laptop  999.99  Electronics
1       Shirt   29.99      Fashion
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics

## Task 1

In [ ]:
greater_than_fifty = df.loc[(df['Category'].isin(["Electronics", "Fashion"])) & (df['Price'] > 50)]
greater_than_fifty

      Product   Price     Category
0      Laptop  999.99  Electronics
2  Smartphone  599.99  Electronics
3       Shoes   89.99      Fashion
4  Headphones  199.99  Electronics

## Task 2

In [26]:
data1 = { 'CustomerID': [1, 2, 3, 4], 'Name': ['John Doe', 'Jane Smith', 'Alice Johnson', 'Bob Brown'], 'Address': ['123 Elm St', '456 Oak St', '789 Pine St', '101 Maple St'] }

data2 = { 'CustomerID': [1, 2, 1, 3], 'OrderDate': ['2024-01-01', '2024-01-05', '2024-01-10', '2024-01-15'], 'TotalAmount': [100.50, 200.75, 150.25, 300.00]}

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

merged_df = pd.merge(df1, df2, on='CustomerID')

In [27]:
merged_df

   CustomerID           Name      Address   OrderDate  TotalAmount
0           1       John Doe   123 Elm St  2024-01-01       100.50
1           1       John Doe   123 Elm St  2024-01-10       150.25
2           2     Jane Smith   456 Oak St  2024-01-05       200.75
3           3  Alice Johnson  789 Pine St  2024-01-15       300.00

## Task 3

In [5]:
data = {
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West'],
    'Sales': [150, 200, 250, 300, 350, 400, 450, 500],
    'Quarter': ['Q1', 'Q1', 'Q1', 'Q1', 'Q2', 'Q2', 'Q2', 'Q2']
}

In [10]:
df = pd.DataFrame(data)

grouped = df.groupby('Region').agg({'Sales': ['sum', 'mean']})
grouped.head()

       Sales
         sum   mean
Region
East     700  350.0
North    500  250.0
South    600  300.0
West     800  400.0

# Final task

In [11]:
the_dict = {
    'name': [],
    'roll': [],
    'address': [],
    'age': []
}

In [13]:
for i in range(10):
    print(f"For person {i}")
    name = input(f"Enter name: ")
    the_dict['name'].append(name)
    roll = input(f"Enter roll number: ")
    the_dict['roll'].append(roll)
    address = input(f"Enter address: ")
    the_dict['address'].append(address)
    age = input(f"Enter age: ")
    the_dict['age'].append(age)

For person 0
For person 1
For person 2
For person 3
For person 4
For person 5
For person 6
For person 7
For person 8
For person 9

In [14]:
the_dict

{'name': ['Ram',
  'Laxman',
  'Sita',
  'Krish',
  'Lucky',
  'Hari',
  'Kamal',
  'Binod',
  'Umang',
  'Ishan'],
 'roll': ['1', '2', '3', '4', '5', '6', '9', '24', '34', '67'],
 'address': ['Kathmandu',
  'Birgunj',
  'Kathmandu',
  'Manang',
  'Darchula',
  'Dhading',
  'Rasuwa',
  'Tanahun',
  'Hetauda',
  'Okhaldhunga'],
 'age': ['32', '22', '23', '35', '23', '39', '74', '38', '8', '78']}

In [15]:
df = pd.DataFrame(the_dict)
df.head()

     name roll    address age
0     Ram    1  Kathmandu  32
1  Laxman    2    Birgunj  22
2    Sita    3  Kathmandu  23
3   Krish    4     Manang  35
4   Lucky    5   Darchula  23

In [20]:
df['age'] = df['age'].astype('int')

In [23]:
df.loc[df['age'] <= 15, 'category'] = 'Junior'
df.loc[(df['age'] > 15) & (df['age'] <= 25), 'category'] = 'Mid'
df.loc[df['age'] > 25, 'category'] = 'Senior'
df

     name roll      address  age category
0     Ram    1    Kathmandu   32   Senior
1  Laxman    2      Birgunj   22      Mid
2    Sita    3    Kathmandu   23      Mid
3   Krish    4       Manang   35   Senior
4   Lucky    5     Darchula   23      Mid
5    Hari    6      Dhading   39   Senior
6   Kamal    9       Rasuwa   74   Senior
7   Binod   24      Tanahun   38   Senior
8   Umang   34      Hetauda    8   Junior
9   Ishan   67  Okhaldhunga   78   Senior